package:
  name: fermi-glast
  version: "v11r5p3"

source:
  git_url: https://github.com/Areustle/fermi-glast.git

build:
  number: 1

requirements:
  build:
    - heacore
    - f2c
    - minuit2
    - python
    - astropy
    - cppunit
    - clhep
    - distribute
    - fftw
    - gsl
    - matplotlib
    - numpy
    - pmw
    - scipy
    - swig
    - xerces-c
    - healpix_cxx
    - wcslib

  run:
    - heacore
    - f2c
    - minuit2
    - python
    - astropy
    - cppunit
    - clhep
    - distribute
    - fftw
    - gsl
    - matplotlib
    - numpy
    - pmw
    - scipy
    - swig
    - xerces-c
    - healpix_cxx
    - wcslib

